"""
Management command to update existing staff records with autogenerated employee IDs
Run this once to update all existing staff records:
python manage.py update_employee_ids
"""
from django.core.management.base import BaseCommand
from django.db.models import Q
from slmsapp.models import Employee


class Command(BaseCommand):
    help = 'Update existing staff records with autogenerated employee IDs'

    def add_arguments(self, parser):
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Show what would be updated without actually updating',
        )
        parser.add_argument(
            '--force',
            action='store_true',
            help='Force update even if employee_id already exists',
        )

    def handle(self, *args, **options):
        dry_run = options['dry_run']
        force = options['force']
        
        # Get all staff records
        staff_without_id = Employee.objects.filter(
            Q(employee_id__isnull=True) | Q(employee_id='')
        )
        staff_with_id = Employee.objects.exclude(
            Q(employee_id__isnull=True) | Q(employee_id='')
        )
        
        total_without = staff_without_id.count()
        total_with = staff_with_id.count()
        
        self.stdout.write(f'Found {total_without} staff records without employee ID')
        self.stdout.write(f'Found {total_with} staff records with existing employee ID')
        
        if dry_run:
            self.stdout.write(self.style.WARNING('DRY RUN MODE - No changes will be made'))
        
        updated_count = 0
        skipped_count = 0
        
        # Update staff without employee IDs
        for staff in staff_without_id:
            new_id = Employee.generate_employee_id()
            if dry_run:
                self.stdout.write(
                    f'Would update: {employee.admin.username} -> {new_id}'
                )
            else:
                employee.employee_id = new_id
                staff.save(update_fields=['employee_id'])
                self.stdout.write(
                    self.style.SUCCESS(
                        f'Updated: {employee.admin.username} -> {new_id}'
                    )
                )
            updated_count += 1
        
        # Optionally update staff with existing IDs (if force flag is set)
        if force:
            self.stdout.write(self.style.WARNING('Force mode: Updating all staff records...'))
            for staff in staff_with_id:
                new_id = Employee.generate_employee_id()
                if dry_run:
                    self.stdout.write(
                        f'Would update: {employee.admin.username} ({employee.employee_id}) -> {new_id}'
                    )
                else:
                    old_id = employee.employee_id
                    employee.employee_id = new_id
                    staff.save(update_fields=['employee_id'])
                    self.stdout.write(
                        self.style.SUCCESS(
                            f'Updated: {employee.admin.username} ({old_id}) -> {new_id}'
                        )
                    )
                updated_count += 1
        else:
            skipped_count = total_with
            self.stdout.write(
                self.style.WARNING(
                    f'Skipped {skipped_count} staff records with existing IDs. '
                    f'Use --force to update them as well.'
                )
            )
        
        if dry_run:
            self.stdout.write(
                self.style.WARNING(
                    f'\nDRY RUN: Would update {updated_count} record(s)'
                )
            )
        else:
            self.stdout.write(
                self.style.SUCCESS(
                    f'\nSuccessfully updated {updated_count} staff record(s)'
                )
            )
            if skipped_count > 0:
                self.stdout.write(
                    self.style.WARNING(
                        f'Skipped {skipped_count} record(s) with existing IDs'
                    )
                )

