# Generated by Django 5.2.8 on 2025-11-21 18:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_leave_data_forward(apps, schema_editor):
    """
    Before converting leave_type from CharField to ForeignKey:
    1. Copy all leave_type values to leave_type_name
    2. Create LeaveType records for all unique leave types
    """
    Staff_Leave = apps.get_model('slmsapp', 'Staff_Leave')
    LeaveType = apps.get_model('slmsapp', 'LeaveType')
    
    # Get all unique leave types from existing records using raw SQL
    # At this point, leave_type is still a CharField
    leave_types_set = set()
    
    with schema_editor.connection.cursor() as cursor:
        # Get distinct leave_type values
        cursor.execute("SELECT DISTINCT leave_type FROM slmsapp_staff_leave WHERE leave_type IS NOT NULL AND leave_type != ''")
        rows = cursor.fetchall()
        leave_types_set = {row[0] for row in rows if row[0] and row[0].strip()}
    
    # Update leave_type_name for all records using raw SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE slmsapp_staff_leave 
            SET leave_type_name = leave_type 
            WHERE leave_type IS NOT NULL AND leave_type != '' 
            AND (leave_type_name IS NULL OR leave_type_name = '')
        """)
    
    # Create LeaveType records for all unique types found
    for lt_name in leave_types_set:
        if lt_name and lt_name.strip():
            LeaveType.objects.get_or_create(
                name=lt_name.strip(),
                defaults={
                    'max_days_per_year': 0,
                    'requires_approval': True,
                    'is_active': True,
                }
            )


def migrate_leave_data_backward(apps, schema_editor):
    """
    Reverse migration - not really needed but required
    """
    pass


def set_leave_type_to_empty(apps, schema_editor):
    """
    Set all leave_type CharField values to empty string before converting to ForeignKey
    This allows the AlterField to proceed without foreign key constraint errors
    """
    with schema_editor.connection.cursor() as cursor:
        # Set leave_type to empty string - we'll populate the FK later based on leave_type_name
        cursor.execute("UPDATE slmsapp_staff_leave SET leave_type = ''")


def populate_leave_type_fk(apps, schema_editor):
    """
    After AlterField, populate the leave_type ForeignKey based on leave_type_name
    """
    Staff_Leave = apps.get_model('slmsapp', 'Staff_Leave')
    LeaveType = apps.get_model('slmsapp', 'LeaveType')
    
    # Update all Staff_Leave records to link to the correct LeaveType
    for leave in Staff_Leave.objects.all():
        if leave.leave_type_name:
            try:
                leave_type = LeaveType.objects.get(name=leave.leave_type_name.strip())
                leave.leave_type = leave_type
                leave.save(update_fields=['leave_type'])
            except LeaveType.DoesNotExist:
                # If LeaveType doesn't exist, create it
                leave_type = LeaveType.objects.create(
                    name=leave.leave_type_name.strip(),
                    max_days_per_year=0,
                    requires_approval=True,
                    is_active=True,
                )
                leave.leave_type = leave_type
                leave.save(update_fields=['leave_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0006_staff_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_days_per_year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='staff_leave',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Leave', 'verbose_name_plural': 'Staff Leaves'},
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Intern', 'Intern')], default='Full-time', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='approved_by_department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves_dh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='approved_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='leave_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'Staff'), (1, 'Super Admin'), (4, 'HR'), (3, 'Department Head')], default=2, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='slmsapp.staff'),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='slmsapp.department'),
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_heads', to='slmsapp.department')),
            ],
            options={
                'verbose_name': 'Department Head',
                'verbose_name_plural': 'Department Heads',
            },
        ),
        # Data migration: Copy leave_type to leave_type_name and create LeaveType records BEFORE altering the field
        migrations.RunPython(
            code=migrate_leave_data_forward,
            reverse_code=migrate_leave_data_backward,
        ),
        # First, alter the CharField to allow NULL
        migrations.AlterField(
            model_name='staff_leave',
            name='leave_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Now set all values to empty string (we'll use leave_type_name instead)
        migrations.RunPython(
            code=lambda apps, schema_editor: set_leave_type_to_empty(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        # Now convert to ForeignKey
        migrations.AlterField(
            model_name='staff_leave',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slmsapp.leavetype'),
        ),
        # Now populate the ForeignKey based on leave_type_name
        migrations.RunPython(
            code=populate_leave_type_fk,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_entitled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='slmsapp.staff')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slmsapp.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Entitlement',
                'verbose_name_plural': 'Leave Entitlements',
                'unique_together': {('staff', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('days_entitled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_remaining', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='slmsapp.staff')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slmsapp.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('staff', 'leave_type', 'year')},
            },
        ),
    ]
