# Generated by Django 5.2.8 on 2025-11-21 18:59

from django.db import migrations


def migrate_leave_types_data(apps, schema_editor):
    """
    Migrate existing leave_type string values to LeaveType model
    This runs BEFORE the AlterField in migration 0007, so we need to handle it differently.
    Actually, this runs AFTER 0007, so leave_type is already a ForeignKey.
    We need to handle the case where the migration failed.
    """
    # This migration runs after 0007, so if 0007 failed, we need to handle it
    # But actually, if 0007 failed, this won't run either
    # So we need to fix 0007 itself
    
    # For now, this is a placeholder that will create LeaveTypes if they don't exist
    # and update leave_type_name from the old leave_type field
    pass


def reverse_migrate_leave_types_data(apps, schema_editor):
    """
    Reverse migration - not needed but required for rollback
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0007_department_leavetype_systemsettings_and_more'),
    ]

    operations = [
        # This migration is a placeholder - the real fix needs to be in 0007
    ]
