# Generated by Django 5.2.8 on 2025-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0008_migrate_leave_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'Department Head'), (1, 'Super Admin'), (4, 'HR'), (2, 'Staff')], default=2, max_length=50),
        ),
    ]
