# Generated by Django 5.2.8 on 2025-11-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'Department Head'), (2, 'Staff'), (4, 'HR'), (1, 'Super Admin')], default=2, max_length=50),
        ),
    ]
