# Generated by Django 5.2.8 on 2025-11-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0010_publicholiday_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'Department Head'), (4, 'HR'), (1, 'Super Admin'), (2, 'Staff')], default=2, max_length=50),
        ),
    ]
