# Generated by Django 5.2.8 on 2025-12-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0015_alter_customuser_user_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'Department Head'), (2, 'Staff'), (1, 'Admin'), (4, 'HR')], default=2, max_length=50),
        ),
    ]
