# Generated by Django 5.2.8 on 2025-12-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0016_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(4, 'HR'), (1, 'Admin'), (2, 'Staff'), (3, 'Department Head')], default=2, max_length=50),
        ),
    ]
