# Generated by Django 5.2.8 on 2025-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0018_notification_is_active_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Department Head'), (4, 'HR')], default=2, max_length=50),
        ),
    ]
